### ISSUE TITLE
axios get requests need environment variables

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-react-client#6]
Currently hard coded as localhost:5000

**Comment by pacharanero** [comment]
This is now handled via an Environment variable. cc @andrewpalmeruk @eatyourpeas for info only because the route the ENV var takes to get into the app is arcane and interesting.

Because React apps don't have anything server side to interact with the OS layer, the environment variable is baked in at the stage the app is compiled/built. This means it happens in GitHub as part of the [GH Action](https://github.com/rcpch/digital-growth-charts-react-client/blob/alpha/.github/workflows/alpha_rcpch-dgc-react-client-alpha.yml)

The actual data comes from a part of our Settings in the repo, where we can set [GitHub Secrets](https://github.com/rcpch/digital-growth-charts-react-client/settings/secrets) which are available to the build process.

**IMPORTANT: to change the API which the React client uses, you need to change it in the GitHub Secrets. It will automatically be passed to the Action and then to the live version of the React client running in Azure.** You cannot set environment variables in Azure - although there is the facility to do so, they just don't work because by that point the app is simply static code, nothing can be 'injected'.

This seems to be working for the measurement, charts and spreadsheet endpoints
![image](https://user-images.githubusercontent.com/2348385/91214300-c809dc00-e70a-11ea-9109-85550ef2faa2.png)

![image](https://user-images.githubusercontent.com/2348385/91214281-c2ac9180-e70a-11ea-99df-a544c93233e3.png)

![image](https://user-images.githubusercontent.com/2348385/91214170-9e50b500-e70a-11ea-8e85-fbbdd8371178.png)

**Comment by pacharanero** [comment]
Good progress but not quite done
- [x] add env var handling to the React app
- [x] add the env var to the build environment so the app has it
- [x] test this is working empirically
- [ ] add a test that checks that the environment variable is set 
- [ ] add something in the React app documentation about how to set the env var
- [ ] add internal Meta doc info about deployment
